---
- name: apt upgrade
  apt: 
   upgrade: yes
   force_apt_get: yes

- name: Update apt cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Python 3
  apt:
    name: python3
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install boto3 using pip3
  become: true
  pip:
    name: boto3
    state: present

- name: Install AWS CLI using pip
  become: true
  pip:
    name: awscli
    state: latest
    executable: pip3

- name: install java jre
  apt: 
    name: openjdk-17-jre
    state: present
        
- name: Install Java JDK 17
  apt:
    name: openjdk-17-jdk
    state: present
    install_recommends: no
